version: "3.8"

services:

  nodeserver:
    build:
      context: .
      target: nodejs
    ports:
      - "5000:5000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=node.dev.local
    networks:
      - default
      - outside

networks:
  outside:
    external: true
    name: nginx-proxy
